/*
 * 服务1接口地址 API SPECIFICATION
 * Service one api
 *
 * OpenAPI spec version: v1.0
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package com.example.service_one.client.api;

import com.example.service_one.client.model.Dto;
import org.junit.Ignore;
import org.junit.Test;

/**
 * API tests for User_Api
 */
@Ignore
public class User_ApiTest {

    private final User_Api api = new User_Api();


    /**
     * 根据id查用户
     *
     * @throws ApiException if the Api call fails
     */
    @Test
    public void getUserUsingGETTest() {
        String id = null;
        Dto response = api.getUserUsingGET(id);

        // TODO: test validations
    }

}
